version: '3.7'
services:
  go-api:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    container_name: go-skeleton
    env_file:
      - .env
    ports:
      - 1323:1323
    command: air http
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./:/app

  mysql:
    image: mysql:latest
    container_name: mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: skeleton
    ports:
        - "3306:3306"
    volumes:
        - ./storage/mysql:/var/lib/mysql

networks:
    default:
        name: go-skeleton-network
