[replacers.crud]
".stub" = ""
domain = "{{domain}}"
domainCamelCase = "{{domainCamelCase}}"
domainPascalCase = "{{domainPascalCase}}"
"{{validatorImport}}" = "\n	\"go-skeleton/application/services\""
"{{validator}}" = "\n	validator services.Validator"
"{{,validator}}" = ", validator services.Validator"
"{{validatorInject}}" = "	validator: validator,"
"{{hsValidator}}" = "hs.validator"
"{{,hsValidator}}" = ", hs.validator"
"{{validatorRule}}" = """errs := r.validator.ValidateStruct(r.Data)
	for _, err := range errs {
		if err != nil {
			return err
		}
	}
"""
"//{{codeGen1}}" = "{{domainCamelCase}}ListRoutes := New{{domainPascalCase}}Routes(Env, deps)\n	$repeat$"
"//{{codeGen2}}" = "\"{{domain}}\": {{domainCamelCase}}ListRoutes,\n		$repeat$"
"//{{codeGen3}}" = "\"go-skeleton/application/domain/{{domain}}\"\n	$repeat$"
"//{{codeGen4}}" = "m.db.Db.Migrator().CreateTable(&{{domain}}.{{domainPascalCase}}{})\n	$repeat$"

[stubs.crud.domain]
toPath = "application/domain/{{domain}}/"
fromPath = "tools/generator/stubs/crud/domain/"
isGenerated = true

[stubs.crud.services]
toPath = "application/services/{{domain}}/"
fromPath = "tools/generator/stubs/crud/services/"
isGenerated = true

[stubs.crud.repositories]
toPath = "pkg/repositories/{{domain}}/"
fromPath = "tools/generator/stubs/crud/repositories/"
isGenerated = true

[stubs.crud.routes]
toPath = "cmd/http/routes/"
fromPath = "tools/generator/stubs/crud/routes/"
isGenerated = true
uniqueDelete = "cmd/http/routes/{{domain}}.go"

[stubs.crud.declarable]
toPath = "cmd/http/routes/declarable.go"
isGenerated = false
deletePatterns = [
	"New{{domainPascalCase}}Routes",
	"\"{{domain}}\": "
]

[stubs.crud.migrator]
toPath = "tools/migrator/migrate.go"
isGenerated = false
deletePatterns = [
	"\"go-skeleton/application/domain/{{domain}}",
	"&{{domain}}.{{domainPascalCase}}{}"
]

[replacers.usecase]
".stub" = ""
usecase = "{{usecase}}"
usecaseCamelCase = "{{usecaseCamelCase}}"
usecasePascalCase = "{{usecasePascalCase}}"
"//{{codeGen1}}" = "{{usecaseCamelCase}}ListRoutes := New{{usecasePascalCase}}Routes(Env, deps)\n	$repeat$"
"//{{codeGen2}}" = "\"{{usecase}}\": {{usecaseCamelCase}}ListRoutes,\n		$repeat$"

[stubs.usecase.services]
toPath = "internal/application/services/{{usecase}}/"
fromPath = "tools/generator/stubs/usecase/services/"
isGenerated = true

[stubs.usecase.routes]
toPath = "cmd/http/routes/"
fromPath = "tools/generator/stubs/usecase/routes/"
isGenerated = true
uniqueDelete = "cmd/http/routes/{{usecase}}.go"

[stubs.usecase.handlers]
toPath = "cmd/http/handlers/"
fromPath = "tools/generator/stubs/usecase/handlers/"
isGenerated = true
uniqueDelete = "cmd/http/handlers/{{usecase}}.go"

[stubs.usecase.declarable]
toPath = "cmd/http/routes/declarable.go"
isGenerated = false
deletePatterns = [
	"New{{usecasePascalCase}}Routes",
	"\"{{usecase}}\": "
]
