replacers:
    domain: "{{domain}}"
    domainCap: "{{domainCap}}"

stubs:
    domain:
        toPath: "application/domain/{{domain}}/"
        fromPath: "tools/generator/stubs/domain/"
    services:
        toPath: "application/domain/{{domain}}/"
        fromPath: "tools/generator/stubs/domain/"
    repositories:
        toPath: "application/domain/{{domain}}/"
        fromPath: "tools/generator/stubs/domain/"
