[replacers.crud]
domain = "{{domain}}"
domainCap = "{{domainCap}}"
".stub" = ""
domainCamelCase = "{{domainCamelCase}}"
domainPascalCase = "{{domainPascalCase}}"
"//codeGen1" = "My Code..."

[stubs.crud.domain]
toPath = "application/domain/{{domain}}/"
fromPath = "tools/generator/stubs/domain/"

[stubs.crud.services]
toPath = "application/services/{{domain}}/"
fromPath = "tools/generator/stubs/services/"

[stubs.crud.repositories]
toPath = "pkg/repositories/{{domain}}/"
fromPath = "tools/generator/stubs/repositories/"
