[replacers.crud]
domain = "{{domain}}"
domainCamelCase = "{{domainCamelCase}}"
domainPascalCase = "{{domainPascalCase}}"
".stub" = ""
"//codeGen1" = "My Code..."

[stubs.crud.domain]
toPath = "application/domain/{{domain}}/"
fromPath = "tools/generator/stubs/domain/"
isGenerated = true

[stubs.crud.services]
toPath = "application/services/{{domain}}/"
fromPath = "tools/generator/stubs/services/"
isGenerated = true

[stubs.crud.repositories]
toPath = "pkg/repositories/{{domain}}/"
fromPath = "tools/generator/stubs/repositories/"
isGenerated = true
